config/routes.rb
Rails.application.routes.draw do
  resources :children
  resources :artworks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "artworks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artwork.rb
class Artwork < ApplicationRecord
end

app/models/child.rb
class Child < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: %i[ show edit update destroy ]

  # GET /artworks or /artworks.json
  def index
    @artworks = Artwork.all
  end

  # GET /artworks/1 or /artworks/1.json
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks or /artworks.json
  def create
    @artwork = Artwork.new(artwork_params)

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to artwork_url(@artwork), notice: "Artwork was successfully created." }
        format.json { render :show, status: :created, location: @artwork }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artworks/1 or /artworks/1.json
  def update
    respond_to do |format|
      if @artwork.update(artwork_params)
        format.html { redirect_to artwork_url(@artwork), notice: "Artwork was successfully updated." }
        format.json { render :show, status: :ok, location: @artwork }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artwork.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1 or /artworks/1.json
  def destroy
    @artwork.destroy!

    respond_to do |format|
      format.html { redirect_to artworks_url, notice: "Artwork was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artwork_params
      params.require(:artwork).permit(:draw, :title, :author, :date, :description)
    end
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: %i[ show edit update destroy ]

  # GET /children or /children.json
  def index
    @children = Child.all
  end

  # GET /children/1 or /children/1.json
  def show
  end

  # GET /children/new
  def new
    @child = Child.new
  end

  # GET /children/1/edit
  def edit
  end

  # POST /children or /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        format.html { redirect_to child_url(@child), notice: "Child was successfully created." }
        format.json { render :show, status: :created, location: @child }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1 or /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to child_url(@child), notice: "Child was successfully updated." }
        format.json { render :show, status: :ok, location: @child }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1 or /children/1.json
  def destroy
    @child.destroy!

    respond_to do |format|
      format.html { redirect_to children_url, notice: "Child was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def child_params
      params.require(:child).permit(:name, :firtsName, :age, :picture, :city, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/artworks/_artwork.html.erb
<div class="d-flex justify-content-around flex-wrap">
  <% @artworks.each do |artwork| %>
  
    <div class="card mb-3" style="width: 18rem;">
      <img src="<%= artwork.draw %>" class="card-img-top image-frame">
      <div class="card-body">
        <h5 class="card-title">Title</h5>
        <p class="card-text"><%= artwork.title %></p>
        <h5 class="card-title">Description</h5>
        <p class="card-text"><%= artwork.description %></p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= artwork.date %></li>
      </ul>
      <div class="card-body">
        <a href="#" class="card-link">See the author: <%= artwork.author %></a>
      </div>
    </div>
  <% end %>
</div>

app/views/artworks/_form.html.erb
<%= form_with(model: artwork) do |form| %>
  <% if artwork.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
        <% artwork.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :draw, style: "display: block" %>
    <%= form.text_area :draw %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Modifier l'oeuvre</h1>

<%= render "form", artwork: @artwork %>

<br>

<div>
  <%= link_to "Show this artwork", @artwork %> |
  <%= link_to "Back to artworks", artworks_path %>
</div>

app/views/artworks/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Pitchoun's Museum</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    /* Styles CSS intégrés */
    body {
      background-image: url('https://cdn.midjourney.com/9f27bebe-166e-4b7d-b0b2-d390d24c9968/0_0.png');
      background-size: cover;
      background-position: center;
      font-family: 'Arial', sans-serif;
      color: #333;
      margin: 0;
      padding: 0;
    }
    .navbar {
      background-color: #f8f9fa;
      border-bottom: 1px solid #dee2e6;
    }
    .navbar-brand {
      color: #6c757d;
      font-weight: bold;
      font-size: 1.8rem;
      text-transform: uppercase;
      transition: all 0.3s ease;
    }
    .navbar-brand:hover {
      color: #495057;
      transform: scale(1.1);
    }
    .nav-link {
      color: #495057 !important;
      font-weight: bold;
      text-transform: uppercase;
      transition: color 0.3s ease;
    }
    .nav-link:hover {
      color: #343a40 !important;
      transform: scale(1.1);
    }
    h1 {
      background-color: #f8f9fa;
      border: 2px solid #6c757d;
      padding: 30px;
      text-align: center;
      margin-top: 50px;
      color: #495057;
      border-radius: 15px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      animation: fadeInDown 1s ease;
    }
    h2 {
      background-color: #f8f9fa;
      border: 2px solid #6c757d;
      padding: 20px;
      text-align: center;
      margin-bottom: 50px;
      color: #495057;
      border-radius: 15px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      animation: fadeInUp 1s ease;
    }
    .container {
      max-width: 800px;
      margin: auto;
      text-align: center;
    }
    .btn-outline-secondary {
      color: #f8f9fa; /* Text color */
      background-color: #6c757d; /* Button background color */
      border-color: #6c757d; /* Border color */
      transition: all 0.3s ease;
      border-radius: 30px;
      font-size: 1.2rem;
    }
    .btn-outline-secondary:hover {
      background-color: #343a40; /* Button background color on hover */
      color: #f8f9fa; /* Text color on hover */
      transform: scale(1.1) rotate(5deg);
    }
    .btn-outline-secondary:focus {
      box-shadow: 0 0 0 0.2rem rgba(108, 117, 125, 0.5);
    }

    /* Animations */
    @keyframes fadeInDown {
      from {
        opacity: 0;
        transform: translateY(-50px);
      }
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }
    @keyframes fadeInUp {
      from {
        opacity: 0;
        transform: translateY(50px);
      }
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }

    /* Animation bouton */
    .btn-outline-secondary:hover {
      animation: pulse 0.5s infinite alternate;
    }
    @keyframes pulse {
      to {
        transform: scale(1.1);
        box-shadow: 0 0 0 0.2rem rgba(108, 117, 125, 0.5);
      }
    }
  </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Pitchoun's Museum</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container">
    <h1>Welcome to Pitchoun's Museum</h1>
    <h2>Discover a world of creativity and imagination!</h2>

    <div class="mb-5">
      <a class="btn btn-outline-secondary" href="<%= new_child_path %>">Create a new profile for your child</a>
    </div>

    <div id="artworks">
      <% @artworks.each do |artwork| %>
        <%= render artwork %>
        <p>
          <%= link_to "Show this artwork", artwork %>
        </p>
      <% end %>
    </div>
    
    <div class="mb-5">
      <a class="btn btn-outline-secondary" href="<%= new_artwork_path %>">Create a new artwork</a>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/artworks/new.html.erb
<h1>Nouvelle oeuvre</h1>

<%= render "form", artwork: @artwork %>

<br>

<div>
  <%= link_to "Back to artworks", artworks_path %>
</div>

app/views/artworks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artwork %>

<div>
  <%= link_to "Edit this artwork", edit_artwork_path(@artwork) %> |
  <%= link_to "Back to artworks", artworks_path %>

  <%= button_to "Destroy this artwork", @artwork, method: :delete %>
</div>

app/views/children/_child.html.erb
<div id="<%= dom_id child %>">
  <p>
    <strong>Name:</strong>
    <%= child.name %>
  </p>

  <p>
    <strong>Firtsname:</strong>
    <%= child.firtsName %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= child.age %>
  </p>

  <p>
    <strong>Picture:</strong>
    <img src="<%= child.picture %>">
  </p>

  <p>
    <strong>City:</strong>
    <%= child.city %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= child.country %>
  </p>

</div>

app/views/children/_form.html.erb
<%= form_with(model: child) do |form| %>
  <% if child.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
        <% child.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :firtsName, style: "display: block" %>
    <%= form.text_field :firtsName %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :picture, style: "display: block" %>
    <%= form.text_area :picture %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render "form", child: @child %>

<br>

<div>
  <%= link_to "Show this child", @child %> |
  <%= link_to "Back to children", children_path %>
</div>

app/views/children/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Children</h1>



<div id="children">
  <% @children.each do |child| %>
    <%= render child %>
    <p>
      <%= link_to "Show this child", child %>
    </p>
  <% end %>
</div>

<%= link_to "New child", new_child_path %>

app/views/children/new.html.erb
<h1>New child</h1>

<%= render "form", child: @child %>

<br>

<div>
  <%= link_to "Back to children", children_path %>
</div>

app/views/children/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @child %>

<div>
  <%= link_to "Edit this child's profil", edit_child_path(@child) %> |
  <%= link_to "Back to children", children_path %>

<<<<<<< HEAD
  <%= button_to "Destroy this child", @child, method: :delete %>
</div>
=======
  <%= button_to "Delete this child's profil", @child, method: :delete %>
</div>
>>>>>>> cdd8d5069b2589a78a373aee613f7f74b413048a

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pitchoun</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>